#!/bin/bash

# The top-level script to read Master-Index and generate all the
# indexes/ files, including Master-Index.xml. It also updates the RSS
# feed.
# (Run this as root, please.)

# The -a argument removes build.lasttime, which means that ifmap.py
# will regenerate all index pages instead of just the most recent changes.
# The -s argument rebuilds the search index as well.

# Note that this takes roughly 15 seconds to run, if the checksum cache
# (htdocs/checksum-cache.txt) already exists. Recreating the cache
# from scratch takes more like 150 seconds.
# (That's as of 2023. No doubt the times will creep up in future years.)

while getopts "as" flag; do
    if [ $flag = "a" ]; then
        allflag=-a
    fi
    if [ $flag = "s" ]; then
        searchflag=-s
    fi
done

# Protect this script from running if it (or build-indexes) is already
# running. (It will fail if build.lock already exists.)
set -o noclobber
if { > /var/ifarchive/htdocs/build.lock ; } then
  :
else
  echo 'Build script is already running'
  ls -l /var/ifarchive/htdocs/build.lock
  exit
fi
set +o noclobber

# Build Master-Index.xml, all the index .html files, the metadata files,
# and the RSS feed file.

echo 'Rebuilding indexes...'

if [ $allflag ]; then
  rm -f /var/ifarchive/htdocs/build.lasttime
fi

# Look up the SearchURL key in ifarch.config
SEARCHURL=`/var/ifarchive/bin/configparse.py SearchURL /search`

touch /var/ifarchive/htdocs/build.lasttime.tmp

/var/ifarchive/bin/ifmap.py --index /var/ifarchive/htdocs/if-archive/Master-Index --src /var/ifarchive/lib/ifmap --tree /var/ifarchive/htdocs --since /var/ifarchive/htdocs/build.lasttime --searchurl $SEARCHURL

mv /var/ifarchive/htdocs/build.lasttime.tmp /var/ifarchive/htdocs/build.lasttime

# Make sure those files have the correct group and mode.

cd /var/ifarchive/htdocs/indexes
find . -type f -print0 | xargs -0 chmod 664
find . -type f -print0 | xargs -0 chgrp ifarchive
find . -type d -print0 | xargs -0 chmod 775
find . -type d -print0 | xargs -0 chgrp ifarchive

cd /var/ifarchive/htdocs/metadata
find . -type f -print0 | xargs -0 chmod 664
find . -type f -print0 | xargs -0 chgrp ifarchive
find . -type d -print0 | xargs -0 chmod 775
find . -type d -print0 | xargs -0 chgrp ifarchive

# Tell Unbox that Master-Index.xml has updated.
unboxkey=$(sed -E -n 's/UnboxRefreshKey[[:space:]]*=[[:space:]]*([a-zA-Z0-9-]*)/\1/p' /var/ifarchive/lib/ifarch.config)

if [ $unboxkey ]; then
  echo -n 'Unbox: '
  curl --silent --data "key=$unboxkey" "https://unbox.ifarchive.org/?recheck_index"
  echo
else
  echo 'Not notifying Unbox'
fi

if [ $searchflag ]; then
  echo 'Updating search index...'
  python3 /var/ifarchive/wsgi-bin/search.wsgi build
fi

echo 'Done.'

# Clean up the lock file.

rm /var/ifarchive/htdocs/build.lock
