#!/bin/bash

# A wrapper script which runs make-master-index followed by build-indexes,
# but in the background. This script can therefore be invoked by the
# admin server tool without blocking httpd.

( /var/ifarchive/bin/make-master-index ; /var/ifarchive/bin/build-indexes ) &> /var/ifarchive/htdocs/build.out &
