#!/bin/bash

# A wrapper script which runs make-master-index followed by build-indexes,
# but in the background. This script can therefore be invoked by the
# admin server tool without blocking httpd.

# We pass the -a (rebuild all) and -s (rebuild search index) args down
# to build-indexes.

while getopts "as" flag; do
    if [ $flag = "a" ]; then
        allflag=-a
    fi
    if [ $flag = "s" ]; then
        searchflag=-s
    fi
done

(
    /var/ifarchive/bin/make-master-index
    /var/ifarchive/bin/build-indexes $allflag $searchflag
) &> /var/ifarchive/htdocs/build.out &
