#!/bin/bash

python3 make-master-index.py testdata > testdata/if-archive/Master-Index

# The ifmap.py script looks at file timestamps to decide the "last updated"
# date of each file. Git doesn't preserve file timestamps, so we need
# to manually set them to known values.
python3 testdata/set-timestamps.py

# Generate the index files.
python3 ifmap.py --src lib --index testdata/if-archive/Master-Index --tree testdata --curdate 2018-11-15T12:00:00Z

