#!/bin/bash

# Sync the files tree (not indexes or other material) to an AWS bucket.
# The bucket is configured with versioning and a 7-day expiration for
# old file versions, so we get that much rolling history.

# As of late 2024, this takes about 90 seconds to run for a no-change
# sync.

# This requires secret credentials, so it must be run as root.

# Requires rclone 1.53 or later.
# /var/ifarchive/lib/rclone.conf: rclone configuration (names AWS as the provider)
# /var/ifarchive/lib/aws.config: AWS access keys (must be root to read)

/usr/local/bin/rclone --verbose --config /var/ifarchive/lib/rclone.conf --s3-shared-credentials-file /var/ifarchive/lib/aws.config sync /var/ifarchive/htdocs/if-archive s3:iftf-ifarchive-backup --checksum --links --checkers 50 --transfers 10 &>> /var/ifarchive/logs/nightly-backup.log

# Docs suggest a fast "top-up" of recent files, and then a full sync less often. I haven't set that up yet. See: https://rclone.org/s3/
